/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import controlador.Controlador;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel
 */
public class GameInterface extends javax.swing.JFrame {
    Controlador control = new Controlador();
    int barcos;
    /**
     * Creates new form GameInterface
     */
    int c1=0,c2=0,c3=0;
    static int mat[][] = new int[10][10];
    static char tabuleiro[][] = new char[10][10];
    int tam = 10;
    
    public GameInterface() {
        initComponents();
        barcos=0;
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        root = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lb1 = new javax.swing.JTextArea();
        couracado = new javax.swing.JRadioButton();
        cruzador = new javax.swing.JRadioButton();
        submarino = new javax.swing.JRadioButton();
        lb2 = new javax.swing.JLabel();
        portaaviao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lb3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        fogo = new javax.swing.JButton();
        alerta = new javax.swing.JLabel();
        vez = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        root.setLayout(new java.awt.CardLayout());

        jButton1.setText("JOGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CONFIGURAÇÕES");

        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 358, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
        );

        root.add(jPanel1, "card2");

        x.setAutoscrolls(false);
        x.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xFocusGained(evt);
            }
        });

        y.setAutoscrolls(false);
        y.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yFocusGained(evt);
            }
        });

        jButton4.setText("Posicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lb1.setEditable(false);
        lb1.setColumns(20);
        lb1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb1.setRows(5);
        jScrollPane1.setViewportView(lb1);

        buttonGroup1.add(couracado);
        couracado.setText("Couraçado");

        buttonGroup1.add(cruzador);
        cruzador.setText("Cruzador");

        buttonGroup1.add(submarino);
        submarino.setSelected(true);
        submarino.setText("Submarino");

        lb2.setForeground(new java.awt.Color(255, 0, 0));
        lb2.setText("Posição Inválida");

        buttonGroup1.add(portaaviao);
        portaaviao.setText("Porta Aviões");

        jLabel2.setText("Cord X:");

        jLabel3.setText("Cord Y:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(submarino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cruzador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(couracado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portaaviao))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couracado)
                    .addComponent(submarino)
                    .addComponent(portaaviao)
                    .addComponent(cruzador))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(lb2)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        root.add(jPanel3, "posicionar");

        lb3.setEditable(false);
        lb3.setColumns(20);
        lb3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb3.setRows(5);
        jScrollPane2.setViewportView(lb3);

        jLabel4.setText("Cord X:");

        x1.setAutoscrolls(false);
        x1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                x1FocusGained(evt);
            }
        });

        jLabel5.setText("Cord Y:");

        y1.setAutoscrolls(false);
        y1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                y1FocusGained(evt);
            }
        });

        fogo.setText("FOGO!");
        fogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fogoActionPerformed(evt);
            }
        });

        alerta.setText("jLabel6");

        vez.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fogo))
                    .addComponent(alerta)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vez))
                .addGap(0, 301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vez)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(fogo))
                .addGap(18, 18, 18)
                .addComponent(alerta)
                .addGap(0, 115, Short.MAX_VALUE))
        );

        root.add(jPanel2, "novojogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Carregando load = new Carregando(this, true);
        //load.setVisible(true);
        if(control.fila()){
            //load.dispose();
            CardLayout c = (CardLayout) root.getLayout();
            c.show(root, "posicionar");
            lb1.setText(printar());
            lb2.setVisible(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private String printar(){
        int i,j;
        String  sla = "";
        for(i=0;i<tam;i++){
            for(j=0;j<tam;j++){
              sla += String.valueOf(mat[i][j])+"   ";  
            }
            sla += "\n";
        }
        return sla;
    }
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        control.desconectar();
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i;
        int row = Integer.parseInt(x.getText());
        int col = Integer.parseInt(y.getText());
        if(row<10){
        buttonGroup1.add(couracado);
        buttonGroup1.add(cruzador);
        buttonGroup1.add(submarino);
        if(couracado.isSelected()==true && couracado.isEnabled()==true){
            lb2.setVisible(false);
            if(col+2<10){
            for(i=0;i<3;i++)
                if(mat[row][col+i] == 1)
                    i=4;
            if(i<4){
                for(i=0;i<3;i++)
                    mat[row][col+i] = 1;
                control.apontar(row, col, 2);
                barcos++;
                c2++;
                if(c2==2)
                couracado.setEnabled(false);
            }
            else
                lb2.setVisible(true);
            }
            else
                lb2.setVisible(true);
        }
        if(cruzador.isSelected()==true && cruzador.isEnabled()==true){
            lb2.setVisible(false);
            if(col+1<10){
           for(i=0;i<2;i++)
                if(mat[row][col+i] == 1)
                    i=4;
            if(i<4){
            for(i=0;i<2;i++)
                mat[row][col+i] = 1;
            control.apontar(row, col, 1);
            barcos++;
            c3++;
                if(c3==3)
            cruzador.setEnabled(false);
            }
             else
               lb2.setVisible(true);
        }
             else
               lb2.setVisible(true);
        }
        if(submarino.isSelected()==true && submarino.isEnabled()==true){
            lb2.setVisible(false);
            if(col<10 && mat[row][col]!=1){
            mat[row][col] = 1;
            control.apontar(row, col, 0);
            barcos++;
            c1++;
            }
            else 
                lb2.setVisible(true);
            if(c1==4)
                submarino.setEnabled(false);
        }
        if(portaaviao.isSelected()==true && portaaviao.isEnabled()==true){
            lb2.setVisible(false);
            if(col+3<10){
            for(i=0;i<4;i++)
                if(mat[row][col+i] == 1)
                    i=5;
            if(i<5){
                for(i=0;i<4;i++)
                    mat[row][col+i] = 1;
                control.apontar(row, col, 3);
                barcos++;
                portaaviao.setEnabled(false);
            }
            else
                lb2.setVisible(true);
            }
            else
                lb2.setVisible(true);
        }
        }
        else{
            lb2.setVisible(true);
        }
        lb1.setText(printar());
//        if(!portaaviao.isVisible() && !submarino.isVisible() && !cruzador.isVisible()
//                && !couracado.isVisible()){
        verificaPronto();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void verificaPronto(){
        if(barcos == 2 ) { 
            lb1.setText(printar());
            novoJogo(control.toPronto());
            if(control.verificarVez()){
                vez.setText("Sua Vez de Jogar");
            }else{
                vez.setText("Não é sua vez de Jogar");
            }
        }
    }
    private void xFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xFocusGained
        // TODO add your handling code here:
        x.setText("");
    }//GEN-LAST:event_xFocusGained

    private void yFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yFocusGained
        y.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_yFocusGained

    private void x1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_x1FocusGained
        // TODO add your handling code here:
        x1.setText("");
    }//GEN-LAST:event_x1FocusGained

    private void y1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_y1FocusGained
        // TODO add your handling code here:
        y1.setText("");
    }//GEN-LAST:event_y1FocusGained

    private void fogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fogoActionPerformed
        // TODO add your handling code here:
        int x;
        int y;
        if(control.verificarVez()){
                vez.setText("Sua Vez de Jogar");
        }else{
                vez.setText("Não é sua vez de Jogar");
                return;
        }
        try{
            x = Integer.parseInt(x1.getText());
            y = Integer.parseInt(y1.getText());
            if(x>=tam || y>=tam){
                JOptionPane.showMessageDialog(this, "Insira Numeros Validos", "ATENÇÃO", HEIGHT);
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Insira Numeros Validos", "ATENÇÃO", HEIGHT);
            return;
        }
        if(tabuleiro[x][y] == 'O' || tabuleiro[x][y] == 'X'){
            alerta.setText("Campo já atingido");
            return;
        }
        Integer aux = control.fogo(x,y);
        //if(aux !=null){
            if (aux == 2) {
                JOptionPane.showMessageDialog(null, "Você Venceu");
            } else if (aux == 1) {
                tabuleiro[x][y] = '1';
                alerta.setText("Acertou Mizeravi");
                vez.setText("Sua vez de Jogar");
            } else if (aux == 0) {
                alerta.setText("ERROU!");
                tabuleiro[x][y] = 'X';
                vez.setText("Não é sua vez");
            }

            lb3.setText(printarChar());
       // }
    }//GEN-LAST:event_fogoActionPerformed

    private void novoJogo(Boolean pronto){
        if(pronto){
            CardLayout c = (CardLayout) root.getLayout();
            c.show(root, "novojogo");
            int i,j;
            String m= "";
            for(i=0;i<tam;i++){
                for(j=0; j<tam; j++){
                    tabuleiro[i][j] = '0';
                    m += String.valueOf(tabuleiro[i][j])+"  ";
                }
                m+="\n";
            }
            lb3.setText(m);
        }
    }
    
    private String printarChar(){
        int i,j;
        String  sla = "";
        for(i=0;i<tam;i++){
            for(j=0;j<tam;j++){
              sla += String.valueOf(tabuleiro[i][j])+"   ";  
            }
            sla += "\n";
        }
        return sla;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInterface().setVisible(true);
                int i,j,p=0,q=0;
                for(i=0;i<10;i++){
                    for(j=0;j<10;j++){
                        if(i==0){
                            mat[i][j]=p;
                        p++;}
                        if(j==0){
                            mat[i][j]=q;
                            q++;
                        }}}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alerta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton couracado;
    private javax.swing.JRadioButton cruzador;
    private javax.swing.JButton fogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JTextArea lb3;
    private javax.swing.JRadioButton portaaviao;
    private javax.swing.JPanel root;
    private javax.swing.JRadioButton submarino;
    private javax.swing.JLabel vez;
    private javax.swing.JTextField x;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField y;
    private javax.swing.JTextField y1;
    // End of variables declaration//GEN-END:variables
}
